// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrdfmV-KfboDraFZjn89MYdn8Fm2a_v4o',
    appId: '1:115053341718:web:7924de57c2c8f07291d937',
    messagingSenderId: '115053341718',
    projectId: 'fir-flutter-class-84efa',
    authDomain: 'fir-flutter-class-84efa.firebaseapp.com',
    storageBucket: 'fir-flutter-class-84efa.firebasestorage.app',
    measurementId: 'G-XN5EZLGD5L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa8-ETGjpmM0tg1QfPNVxaZYqodI8_7QU',
    appId: '1:115053341718:android:406be9604301bfe891d937',
    messagingSenderId: '115053341718',
    projectId: 'fir-flutter-class-84efa',
    storageBucket: 'fir-flutter-class-84efa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwicTcgkCBbHD5IAyIOB35pEw-nOff1o',
    appId: '1:115053341718:ios:219df59bb353229491d937',
    messagingSenderId: '115053341718',
    projectId: 'fir-flutter-class-84efa',
    storageBucket: 'fir-flutter-class-84efa.firebasestorage.app',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwicTcgkCBbHD5IAyIOB35pEw-nOff1o',
    appId: '1:115053341718:ios:219df59bb353229491d937',
    messagingSenderId: '115053341718',
    projectId: 'fir-flutter-class-84efa',
    storageBucket: 'fir-flutter-class-84efa.firebasestorage.app',
    iosBundleId: 'com.example.fireBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrdfmV-KfboDraFZjn89MYdn8Fm2a_v4o',
    appId: '1:115053341718:web:692654fa297683a391d937',
    messagingSenderId: '115053341718',
    projectId: 'fir-flutter-class-84efa',
    authDomain: 'fir-flutter-class-84efa.firebaseapp.com',
    storageBucket: 'fir-flutter-class-84efa.firebasestorage.app',
    measurementId: 'G-3DVL2P58TF',
  );
}
